[package]
name = "realtime-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0"

#[[bin]]
#name = "realtime-notes"
#path = "src/main.rs"
